meshitero/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :post_images, only: [:new, :create, :index, :show]
  root to: 'homes#top'
  get '/homes/about' => 'homes#about',as: 'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

meshitero/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

meshitero/app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
end

meshitero/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
 has_many :post_images,dependent: :destroy
end

meshitero/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    about_path
  end
  
  protected
  
  def after_sign_out_path_for(resource)
    about_path
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sing_up,keys: [:name])
  end
end

meshitero/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
    
  end
end

meshitero/app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
   def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
  end

  def index
  end

  def show
  end

  private
  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end

end

meshitero/app/helpers/application_helper.rb
module ApplicationHelper
end

meshitero/app/helpers/homes_helper.rb
module HomesHelper
end

meshitero/app/helpers/post_images_helper.rb
module PostImagesHelper
end

meshitero/app/views/homes/about.html.erb
<h1>Aboutページ</h1>

meshitero/app/views/homes/top.html.erb
<h1>Topページ</h1>

meshitero/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshitero</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <li>
          <%= link_to "投稿フォーム", new_post_image_path %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録",new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン",new_user_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

meshitero/app/views/post_images/index.html.erb
<h1>PostImages#index</h1>
<p>Find me in app/views/post_images/index.html.erb</p>

meshitero/app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>

<%= form_with model: @post_image,local:true do |f|  %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>
  
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  
  <h4>説明</h4>
  <%= f.text_area :caption %>
  
  <%= f.submit '投稿' %>
  
<% end %>

meshitero/app/views/post_images/show.html.erb
<h1>PostImages#show</h1>
<p>Find me in app/views/post_images/show.html.erb</p>