bookers/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'homes#top',as: 'root'
  get 'books' => 'books#index', as: 'books'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit',as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
     flash[:notice] = "Book was successfully created."
     redirect_to book_path(@book.id)
   else
     @books = Book.all
     render :index
   end
  end


  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<main class="edit-main">
    <% if @book.errors.any? %>
      <div class="error">
        <%= @book.errors.count %>error has occurred
        <% @book.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
      </div>
      
    <% end %>
    <%= form_with model: @book,url: update_book_path,method: :patch, local: true do |f| %>
      <p>title</p>
      <%= f.text_field :title  %>
      <p>body</p>
      <%= f.text_area :body%>
      <%= f.submit "Update Book", class:"submit" %>
    <% end %>
    <%= link_to "Show",book_path(@book.id) %> |
    <%= link_to "Back",'/books' %>
</main>

bookers/app/views/books/index.html.erb
<h1>Books</h1>
<main class="index-main">
    <table>
      <tr>
        <th class="title">Title</th>
        <th class="body">Body</th>
        <th colspan="3"></th>
      </tr>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td><%= link_to "Show",book_path(book.id) %></td>
          <td><%= link_to "Edit",edit_book_path(book.id) %></td>
          <td><%= link_to "Destroy",destroy_book_path(book.id),method: :delete,"data-confirm"=>"本当に削除しますか？" %></td>
        </tr>
      <% end %>
    </table>

    <h2>New book</h2>
    <% if @book.errors.any? %>
      <div class="error">
        <%= @book.errors.count %>error has occurred
        <% @book.errors.full_messages.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
      </div>
      
    <% end %>

    <%= form_with model: @book,url: '/books',method: :post, local: true do |f| %>
      <p>title</p>
      <%= f.text_field :title,value:"#{@book.title}"  %>
      <p>body</p>
      <%= f.text_area :body, value:"#{@book.body}"%>
      <%= f.submit "Create Book", class:"submit" %>
    <% end %>
</main>

bookers/app/views/books/show.html.erb
<main class="show-main">
  <P><strong>title:</strong> <%= @book.title%></P>
  <P><strong>body:</strong> <%= @book.body%></P>
  <%= link_to "Edit",edit_book_path(@book.id) %> |
  <%= link_to "Back",'/books' %>
</main>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key,value| %>
      <%= content_tag(:p, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>